# Generated by Django 4.2.7 on 2025-10-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Quiz deadline for completion', null=True),
        ),
    ]
