# Generated by Django 4.2.7 on 2025-10-30 01:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Text description used to generate the image')),
                ('image_url', models.URLField(blank=True, help_text='URL of generated image')),
                ('image_file', models.ImageField(blank=True, help_text='Locally stored image file', null=True, upload_to='illustrations/')),
                ('ai_generated', models.BooleanField(default=False)),
                ('generation_prompt', models.TextField(blank=True, help_text='Full prompt used for AI generation')),
                ('generation_service', models.CharField(blank=True, help_text='AI service used (e.g., DALL-E, Stable Diffusion)', max_length=50)),
                ('generation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('order', models.IntegerField(default=0, help_text='Display order in course')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='course_app.course')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
