# Generated by Django 4.2.7 on 2025-10-29 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_app', '0003_workshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['-scheduled_at', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='meeting_url',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='workshop',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshops_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshop',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
