# Generated by Django 4.2.7 on 2025-10-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_workshop_options_remove_workshop_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/images/'),
        ),
    ]
