# Generated by Django 4.2.7 on 2025-10-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_workshop_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='workspaces/images/'),
        ),
    ]
