# Generated by Django 4.2.7 on 2025-10-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_illustration'),
        ('course_app', '0006_workspace_cover_image'),
    ]

    operations = [
    ]
