# Generated by Django 4.2.7 on 2025-10-24 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('whisper', 'Whisper (Speech-to-Text)'), ('gemini', 'Gemini (Text Generation)'), ('huggingface', 'Hugging Face (Image Generation)'), ('face_recognition', 'Face Recognition')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(default=dict)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('audio', 'Audio'), ('video', 'Video')], max_length=50)),
                ('content_data', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_service_used', models.CharField(max_length=50)),
                ('source_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to='course_app.course')),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to='course_app.audioquestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
